spring.application.name=backend
server.port=8081
spring.security.user.name=parola
spring.security.user.password=parola
spring.datasource.url=jdbc:postgresql://localhost:5432/socialnetwork
spring.datasource.username=postgres
spring.datasource.password=postgres

